# Generated by Django 5.1.1 on 2024-09-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('club', models.CharField(max_length=100, verbose_name='Club')),
                ('athlete_event', models.CharField(max_length=60, verbose_name='Athlete Event')),
                ('athlete_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
